Repository krittika2004/AeroSaver, pull requests merged in 2025-04, with the labels that each got.

#30 updated readme
  README.md
Labels: documentation, good first issue, pwoc, easy

#32 added chatbot
  Flight_Prediction_Final/static/dark-mode.js
  Flight_Prediction_Final/templates/index.html
Labels: enhancement, pwoc, hard

#34 added weather prediction feature
  .gitignore
  Flight_Prediction_Final/app.py
  Flight_Prediction_Final/templates/index.html
  Flight_Prediction_Final/templates/weather.html
  package-lock.json
  package.json
Labels: enhancement, pwoc, medium
